name: inventary_app_production
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  get_storage: ^2.0.3
  file_picker: ^5.0.0
  mobile_scanner: ^5.2.3
  rflutter_alert: any
  google_fonts: any
  flutter_sound: ^9.16.0
  flutter_dropdown_search: any
  flutter_overlay_loader: any
  dio: 4.0.0
  fluttertoast: any
  flutter_local_notifications: ^17.2.3
  intl: any
  mime: ^1.0.0
  xml2json: ^5.3.1
  http: any
  csv: ^6.0.0 # For CSV file generation
  pdf: ^3.11.1 # For PDF file generation
  xml: ^6.5.0
  flutter_spinkit: ^5.1.0
  #share_plus: ^10.0.3
  animated_text_kit: ^4.2.1
  workmanager: ^0.5.0
  device_info_plus: ^10.0.0
  connectivity_plus: any
  carousel_slider: any
  purchases_flutter: ^8.1.2
  path_provider: ^2.0.0
  flutter_speed_dial: ^7.0.0
  permission_handler: ^8.1.4+2
  barcode_widget: ^2.0.4
  flutter_email_sender: ^6.0.3
  dropdown_search: ^6.0.1
  flutter_typeahead: ^4.0.0
  audioplayers: any
  open_file: any
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/beep.mp3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"